async function generatePDF() {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const data = collectData();
  const { lift, intake1, intake01, exhaust1, exhaust01, intakeLCA, exhaustLCA } = data;

  const ivo = intakeLCA - (intake1 / 2);
  const ivc = intakeLCA + (intake1 / 2);
  const evo = exhaustLCA - (exhaust1 / 2);
  const evc = exhaustLCA + (exhaust1 / 2);

  doc.setFontSize(14);
  doc.text("Cam Doctor v1 - Valve Timing Report", 20, 20);
  doc.setFontSize(12);
  doc.text(`Valve Lift: ${lift} mm`, 20, 30);
  doc.text(`Intake Duration @1mm: ${intake1} deg`, 20, 40);
  doc.text(`Intake Duration @0.1: ${intake01} deg`, 20, 50);
  doc.text(`Exhaust Duration @1mm: ${exhaust1} deg`, 20, 60);
  doc.text(`Exhaust Duration @0.1: ${exhaust01} deg`, 20, 70);
  doc.text(`Intake Lobe Center Angle: ${intakeLCA} deg`, 20, 80);
  doc.text(`Exhaust Lobe Center Angle: ${exhaustLCA} deg`, 20, 90);
  doc.text(`Intake Opens @ ${ivo}°, Closes @ ${ivc}°`, 20, 100);
  doc.text(`Exhaust Opens @ ${evo}°, Closes @ ${evc}°`, 20, 110);

  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by Cam Doctor v1 | Author: Shafaq Dev", 20, 290);

  doc.save("cam_doctor_result.pdf");
}

function collectData() {
  return {
    lift: parseFloat(document.getElementById("lift").value) || 0,
    intake1: parseFloat(document.getElementById("intake1").value) || 0,
    intake01: parseFloat(document.getElementById("intake01").value) || 0,
    exhaust1: parseFloat(document.getElementById("exhaust1").value) || 0,
    exhaust01: parseFloat(document.getElementById("exhaust01").value) || 0,
    intakeLCA: parseFloat(document.getElementById("intakeLCA").value) || 0,
    exhaustLCA: parseFloat(document.getElementById("exhaustLCA").value) || 0
  };
}

function showResults() {
  const data = collectData();
  const { lift, intake1, intake01, exhaust1, exhaust01, intakeLCA, exhaustLCA } = data;

  const ivo = intakeLCA - (intake1 / 2);
  const ivc = intakeLCA + (intake1 / 2);
  const evo = exhaustLCA - (exhaust1 / 2);
  const evc = exhaustLCA + (exhaust1 / 2);

  const outputDiv = document.getElementById("outputArea");
  outputDiv.innerHTML = `
    <h3>Output Summary</h3>
    <p><strong>Valve Lift:</strong> ${lift} mm</p>
    <p><strong>Intake Duration @1mm:</strong> ${intake1} deg</p>
    <p><strong>Exhaust Duration @1mm:</strong> ${exhaust1} deg</p>
    <p><strong>IVO:</strong> Opens @ ${ivo}°, <strong>IVC:</strong> Closes @ ${ivc}°</p>
    <p><strong>EVO:</strong> Opens @ ${evo}°, <strong>EVC:</strong> Closes @ ${evc}°</p>
  `;
  outputDiv.style.display = "block";
}

function exportAsImage() {
  html2canvas(document.querySelector(".output-area")).then(canvas => {
    const link = document.createElement('a');
    link.download = 'cam_output.png';
    link.href = canvas.toDataURL();
    link.click();
  });
}
